-- ==============================================================
-- Generated by Vitis HLS v2025.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity arith_encode_encode_bit_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    low_read : IN STD_LOGIC_VECTOR (31 downto 0);
    high_read : IN STD_LOGIC_VECTOR (31 downto 0);
    pending_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ob_read : IN STD_LOGIC_VECTOR (31 downto 0);
    nb_read : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    oi_read : IN STD_LOGIC_VECTOR (31 downto 0);
    prob_read : IN STD_LOGIC_VECTOR (31 downto 0);
    bit_r : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of arith_encode_encode_bit_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_C000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000001100000000000000";
    constant ap_const_lv32_1000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_324_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_fu_450_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal range_fu_364_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal range_reg_871 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal split_reg_884 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal r_2_fu_458_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_2_reg_902 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln47_fu_470_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln47_reg_907 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln47_1_fu_474_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln47_1_reg_913 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln48_reg_919 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_923 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_518_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln_fu_595_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln56_1_fu_621_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln33_fu_638_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal pending_0_load44_reg_956 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal pending_0_load_3_reg_961 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_done : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_idle : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_ready : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_ce0 : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_we0 : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_oi_5_out_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_oi_5_out_o_ap_vld : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_nb_5_out_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_nb_5_out_o_ap_vld : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ob_5_out_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ob_5_out_o_ap_vld : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_done : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_idle : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_ready : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_ce0 : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_we0 : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_oi_2_out_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_oi_2_out_o_ap_vld : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_nb_2_out_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_nb_2_out_o_ap_vld : STD_LOGIC;
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ob_2_out_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ob_2_out_o_ap_vld : STD_LOGIC;
    signal oi_5_ph_reg_191 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_5_ph_reg_201 : STD_LOGIC_VECTOR (31 downto 0);
    signal ob_5_ph_reg_213 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_empty_phi_fu_228_p6 : STD_LOGIC_VECTOR (14 downto 0);
    signal empty_reg_225 : STD_LOGIC_VECTOR (14 downto 0);
    signal and_ln55_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_predicate_op128_call_state6 : BOOLEAN;
    signal ap_block_state6_on_subcall_done : BOOLEAN;
    signal ap_phi_mux_empty_45_phi_fu_239_p6 : STD_LOGIC_VECTOR (14 downto 0);
    signal empty_45_reg_236 : STD_LOGIC_VECTOR (14 downto 0);
    signal oi_2_ph_reg_247 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_2_ph_reg_257 : STD_LOGIC_VECTOR (31 downto 0);
    signal ob_2_ph_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start_reg : STD_LOGIC := '0';
    signal out_r_we0_out : STD_LOGIC;
    signal oi_0_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal nb_0_fu_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ob_0_fu_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln34_4_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_fu_653_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_94 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal pending_0_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln56_fu_571_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_ln64_1_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal zext_ln47_fu_785_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_1_fu_426_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_ln64_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal zext_ln59_fu_773_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_fu_419_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_we0_local : STD_LOGIC;
    signal out_r_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln1_fu_526_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_r_ce0_local : STD_LOGIC;
    signal out_r_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1_fu_644_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln41_fu_358_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln42_fu_313_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln42_fu_405_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_fu_408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_1_fu_413_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_478_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_494_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln33_3_fu_510_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln33_4_fu_514_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_543_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln55_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_1_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bit_sel2_fu_577_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln56_2_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_fu_591_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal bit_sel_fu_603_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln56_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln56_1_fu_617_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln33_fu_634_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln_fu_664_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln_fu_664_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal sub_ln63_fu_677_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln63_fu_673_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln62_fu_682_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln62_fu_682_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1_fu_687_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal zext_ln62_fu_697_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln62_fu_701_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln63_fu_677_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln62_fu_701_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln62_fu_706_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1_fu_765_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln2_fu_777_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_condition_70 : BOOLEAN;
    signal ap_condition_66 : BOOLEAN;
    signal ap_condition_671 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component arith_encode_encode_bit_1_Pipeline_VITIS_LOOP_53_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        oi_5_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_5_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_5_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        pending_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        oi_5_out_i : IN STD_LOGIC_VECTOR (31 downto 0);
        oi_5_out_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        oi_5_out_o_ap_vld : OUT STD_LOGIC;
        nb_5_out_i : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_5_out_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        nb_5_out_o_ap_vld : OUT STD_LOGIC;
        ob_5_out_i : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_5_out_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        ob_5_out_o_ap_vld : OUT STD_LOGIC );
    end component;


    component arith_encode_encode_bit_1_Pipeline_VITIS_LOOP_50_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        oi_2_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_2_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_2_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        pending_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        oi_2_out_i : IN STD_LOGIC_VECTOR (31 downto 0);
        oi_2_out_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        oi_2_out_o_ap_vld : OUT STD_LOGIC;
        nb_2_out_i : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_2_out_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        nb_2_out_o_ap_vld : OUT STD_LOGIC;
        ob_2_out_i : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_2_out_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        ob_2_out_o_ap_vld : OUT STD_LOGIC );
    end component;


    component arith_encode_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281 : component arith_encode_encode_bit_1_Pipeline_VITIS_LOOP_53_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start,
        ap_done => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_done,
        ap_idle => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_idle,
        ap_ready => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_ready,
        oi_5_ph => oi_5_ph_reg_191,
        nb_5_ph => nb_5_ph_reg_201,
        ob_5_ph => ob_5_ph_reg_213,
        pending_0 => pending_0_load44_reg_956,
        out_r_address0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_address0,
        out_r_ce0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_ce0,
        out_r_we0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_we0,
        out_r_d0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_d0,
        oi_5_out_i => oi_0_fu_110,
        oi_5_out_o => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_oi_5_out_o,
        oi_5_out_o_ap_vld => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_oi_5_out_o_ap_vld,
        nb_5_out_i => nb_0_fu_118,
        nb_5_out_o => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_nb_5_out_o,
        nb_5_out_o_ap_vld => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_nb_5_out_o_ap_vld,
        ob_5_out_i => ob_0_fu_114,
        ob_5_out_o => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ob_5_out_o,
        ob_5_out_o_ap_vld => grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ob_5_out_o_ap_vld);

    grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297 : component arith_encode_encode_bit_1_Pipeline_VITIS_LOOP_50_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start,
        ap_done => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_done,
        ap_idle => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_idle,
        ap_ready => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_ready,
        oi_2_ph => oi_2_ph_reg_247,
        nb_2_ph => nb_2_ph_reg_257,
        ob_2_ph => ob_2_ph_reg_269,
        pending_0 => pending_0_load_3_reg_961,
        out_r_address0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_address0,
        out_r_ce0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_ce0,
        out_r_we0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_we0,
        out_r_d0 => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_d0,
        oi_2_out_i => oi_0_fu_110,
        oi_2_out_o => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_oi_2_out_o,
        oi_2_out_o_ap_vld => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_oi_2_out_o_ap_vld,
        nb_2_out_i => nb_0_fu_118,
        nb_2_out_o => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_nb_2_out_o,
        nb_2_out_o_ap_vld => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_nb_2_out_o_ap_vld,
        ob_2_out_i => ob_0_fu_114,
        ob_2_out_o => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ob_2_out_o,
        ob_2_out_o_ap_vld => grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ob_2_out_o_ap_vld);

    mul_32s_32s_32_1_1_U59 : component arith_encode_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => range_reg_871,
        din1 => prob_read,
        dout => mul_ln42_fu_313_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_ready = ap_const_logic_1)) then 
                    grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_ready = ap_const_logic_1)) then 
                    grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    empty_45_reg_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln48_reg_919 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln51_reg_923 = ap_const_lv1_0) and (icmp_ln48_reg_919 = ap_const_lv1_0)))) then 
                empty_45_reg_236 <= trunc_ln47_1_reg_913;
            elsif (((ap_const_lv1_1 = and_ln55_fu_565_p2) and (icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                empty_45_reg_236 <= xor_ln_fu_595_p3;
            end if; 
        end if;
    end process;

    empty_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln48_reg_919 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln51_reg_923 = ap_const_lv1_0) and (icmp_ln48_reg_919 = ap_const_lv1_0)))) then 
                empty_reg_225 <= trunc_ln47_reg_907;
            elsif (((ap_const_lv1_1 = and_ln55_fu_565_p2) and (icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                empty_reg_225 <= xor_ln56_1_fu_621_p3;
            end if; 
        end if;
    end process;

    nb_0_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                nb_0_fu_118 <= nb_read;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_nb_2_out_o_ap_vld = ap_const_logic_1) and (icmp_ln48_reg_919 = ap_const_lv1_1))) then 
                nb_0_fu_118 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_nb_2_out_o;
            elsif (((ap_predicate_op128_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_nb_5_out_o_ap_vld = ap_const_logic_1))) then 
                nb_0_fu_118 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_nb_5_out_o;
            end if; 
        end if;
    end process;

    nb_2_ph_reg_257_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_70)) then
                if ((grp_fu_330_p2 = ap_const_lv1_1)) then 
                    nb_2_ph_reg_257 <= ap_const_lv32_0;
                elsif ((grp_fu_330_p2 = ap_const_lv1_0)) then 
                    nb_2_ph_reg_257 <= grp_fu_324_p2;
                end if;
            end if; 
        end if;
    end process;

    nb_5_ph_reg_201_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_66)) then
                if ((grp_fu_330_p2 = ap_const_lv1_1)) then 
                    nb_5_ph_reg_201 <= ap_const_lv32_0;
                elsif ((grp_fu_330_p2 = ap_const_lv1_0)) then 
                    nb_5_ph_reg_201 <= grp_fu_324_p2;
                end if;
            end if; 
        end if;
    end process;

    ob_0_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ob_0_fu_114 <= ob_read;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ob_2_out_o_ap_vld = ap_const_logic_1) and (icmp_ln48_reg_919 = ap_const_lv1_1))) then 
                ob_0_fu_114 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ob_2_out_o;
            elsif (((ap_predicate_op128_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ob_5_out_o_ap_vld = ap_const_logic_1))) then 
                ob_0_fu_114 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ob_5_out_o;
            end if; 
        end if;
    end process;

    ob_2_ph_reg_269_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_70)) then
                if ((grp_fu_330_p2 = ap_const_lv1_1)) then 
                    ob_2_ph_reg_269 <= ap_const_lv32_0;
                elsif ((grp_fu_330_p2 = ap_const_lv1_0)) then 
                    ob_2_ph_reg_269 <= shl_ln33_fu_638_p2;
                end if;
            end if; 
        end if;
    end process;

    ob_5_ph_reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_66)) then
                if ((grp_fu_330_p2 = ap_const_lv1_1)) then 
                    ob_5_ph_reg_213 <= ap_const_lv32_0;
                elsif ((grp_fu_330_p2 = ap_const_lv1_0)) then 
                    ob_5_ph_reg_213 <= or_ln_fu_518_p3;
                end if;
            end if; 
        end if;
    end process;

    oi_0_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oi_0_fu_110 <= oi_read;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_oi_2_out_o_ap_vld = ap_const_logic_1) and (icmp_ln48_reg_919 = ap_const_lv1_1))) then 
                oi_0_fu_110 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_oi_2_out_o;
            elsif (((ap_predicate_op128_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_oi_5_out_o_ap_vld = ap_const_logic_1))) then 
                oi_0_fu_110 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_oi_5_out_o;
            end if; 
        end if;
    end process;

    oi_2_ph_reg_247_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_70)) then
                if ((grp_fu_330_p2 = ap_const_lv1_1)) then 
                    oi_2_ph_reg_247 <= grp_fu_336_p2;
                elsif ((grp_fu_330_p2 = ap_const_lv1_0)) then 
                    oi_2_ph_reg_247 <= oi_0_fu_110;
                end if;
            end if; 
        end if;
    end process;

    oi_5_ph_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_66)) then
                if ((grp_fu_330_p2 = ap_const_lv1_1)) then 
                    oi_5_ph_reg_191 <= grp_fu_336_p2;
                elsif ((grp_fu_330_p2 = ap_const_lv1_0)) then 
                    oi_5_ph_reg_191 <= oi_0_fu_110;
                end if;
            end if; 
        end if;
    end process;

    pending_0_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                pending_0_fu_98 <= pending_read;
            elsif (((ap_const_lv1_1 = and_ln55_fu_565_p2) and (icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                pending_0_fu_98 <= add_ln56_fu_571_p2;
            elsif ((((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln48_reg_919 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln51_reg_923 = ap_const_lv1_0) and (icmp_ln48_reg_919 = ap_const_lv1_0)))) then 
                pending_0_fu_98 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    phi_ln64_1_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                phi_ln64_1_fu_102 <= select_ln43_1_fu_426_p3;
            elsif (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                phi_ln64_1_fu_102 <= zext_ln47_fu_785_p1;
            end if; 
        end if;
    end process;

    phi_ln64_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                phi_ln64_fu_106 <= select_ln43_fu_419_p3;
            elsif (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                phi_ln64_fu_106 <= zext_ln59_fu_773_p1;
            end if; 
        end if;
    end process;

    r_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_fu_94 <= ap_const_lv6_0;
            elsif (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                r_fu_94 <= r_2_reg_902;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln48_reg_919 <= icmp_ln48_fu_488_p2;
                icmp_ln51_reg_923 <= icmp_ln51_fu_504_p2;
                r_2_reg_902 <= r_2_fu_458_p2;
                trunc_ln47_1_reg_913 <= trunc_ln47_1_fu_474_p1;
                trunc_ln47_reg_907 <= trunc_ln47_fu_470_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                pending_0_load44_reg_956 <= pending_0_fu_98;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                pending_0_load_3_reg_961 <= pending_0_fu_98;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                range_reg_871 <= range_fu_364_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                split_reg_884 <= mul_ln42_fu_313_p2(31 downto 12);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, and_ln55_fu_565_p2, ap_CS_fsm_state6, ap_block_state6_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and ((tmp_fu_450_p3 = ap_const_lv1_1) or ((icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln55_fu_565_p2))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln48_fu_488_p2 = ap_const_lv1_1) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((ap_const_lv1_1 = and_ln55_fu_565_p2) and (icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln41_fu_358_p2 <= std_logic_vector(unsigned(high_read) + unsigned(ap_const_lv32_1));
    add_ln43_1_fu_413_p2 <= std_logic_vector(unsigned(add_ln43_fu_408_p2) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln43_fu_408_p2 <= std_logic_vector(unsigned(zext_ln42_fu_405_p1) + unsigned(low_read));
    add_ln56_fu_571_p2 <= std_logic_vector(unsigned(pending_0_fu_98) + unsigned(ap_const_lv32_1));
    add_ln62_fu_701_p1 <= prob_read;
    add_ln62_fu_701_p2 <= std_logic_vector(unsigned(zext_ln62_fu_697_p1) + unsigned(add_ln62_fu_701_p1));
    and_ln55_fu_565_p2 <= (icmp_ln55_fu_553_p2 and icmp_ln55_1_fu_559_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state6_on_subcall_done)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_block_state6_on_subcall_done_assign_proc : process(icmp_ln48_reg_919, grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_done, grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_done, ap_predicate_op128_call_state6)
    begin
                ap_block_state6_on_subcall_done <= (((grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_done = ap_const_logic_0) and (icmp_ln48_reg_919 = ap_const_lv1_1)) or ((ap_predicate_op128_call_state6 = ap_const_boolean_1) and (grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_done = ap_const_logic_0)));
    end process;


    ap_condition_66_assign_proc : process(ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2)
    begin
                ap_condition_66 <= ((icmp_ln51_fu_504_p2 = ap_const_lv1_0) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4));
    end process;


    ap_condition_671_assign_proc : process(ap_CS_fsm_state4, tmp_fu_450_p3, grp_fu_330_p2)
    begin
                ap_condition_671 <= ((grp_fu_330_p2 = ap_const_lv1_1) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4));
    end process;


    ap_condition_70_assign_proc : process(ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2)
    begin
                ap_condition_70 <= ((icmp_ln48_fu_488_p2 = ap_const_lv1_1) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, and_ln55_fu_565_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and ((tmp_fu_450_p3 = ap_const_lv1_1) or ((icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln55_fu_565_p2)))) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_45_phi_fu_239_p6_assign_proc : process(trunc_ln47_1_reg_913, icmp_ln48_reg_919, icmp_ln51_reg_923, ap_CS_fsm_state6, empty_45_reg_236)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln48_reg_919 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln51_reg_923 = ap_const_lv1_0) and (icmp_ln48_reg_919 = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_45_phi_fu_239_p6 <= trunc_ln47_1_reg_913;
        else 
            ap_phi_mux_empty_45_phi_fu_239_p6 <= empty_45_reg_236;
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_228_p6_assign_proc : process(trunc_ln47_reg_907, icmp_ln48_reg_919, icmp_ln51_reg_923, empty_reg_225, ap_CS_fsm_state6)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln48_reg_919 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln51_reg_923 = ap_const_lv1_0) and (icmp_ln48_reg_919 = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_phi_fu_228_p6 <= trunc_ln47_reg_907;
        else 
            ap_phi_mux_empty_phi_fu_228_p6 <= empty_reg_225;
        end if; 
    end process;


    ap_predicate_op128_call_state6_assign_proc : process(icmp_ln48_reg_919, icmp_ln51_reg_923)
    begin
                ap_predicate_op128_call_state6 <= ((icmp_ln51_reg_923 = ap_const_lv1_0) and (icmp_ln48_reg_919 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, and_ln55_fu_565_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and ((tmp_fu_450_p3 = ap_const_lv1_1) or ((icmp_ln51_fu_504_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln55_fu_565_p2))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= pending_0_fu_98;
    ap_return_1 <= ob_0_fu_114;
    ap_return_2 <= nb_0_fu_118;
    ap_return_3 <= oi_0_fu_110;
    ap_return_4 <= phi_ln64_fu_106;
    ap_return_5 <= phi_ln64_1_fu_102;
    ap_return_6 <= select_ln62_fu_706_p3;
    bit_sel2_fu_577_p3 <= phi_ln64_fu_106(14 downto 14);
    bit_sel_fu_603_p3 <= phi_ln64_1_fu_102(14 downto 14);
    grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_ap_start_reg;
    grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_ap_start_reg;
    grp_fu_324_p2 <= std_logic_vector(unsigned(nb_0_fu_118) + unsigned(ap_const_lv32_1));
    grp_fu_330_p2 <= "1" when (grp_fu_324_p2 = ap_const_lv32_8) else "0";
    grp_fu_336_p2 <= std_logic_vector(unsigned(oi_0_fu_110) + unsigned(ap_const_lv32_1));
    icmp_ln48_fu_488_p2 <= "1" when (tmp_2_fu_478_p4 = ap_const_lv17_0) else "0";
    icmp_ln51_fu_504_p2 <= "1" when (tmp_3_fu_494_p4 = ap_const_lv17_0) else "0";
    icmp_ln55_1_fu_559_p2 <= "1" when (unsigned(phi_ln64_1_fu_102) < unsigned(ap_const_lv32_C000)) else "0";
    icmp_ln55_fu_553_p2 <= "0" when (tmp_4_fu_543_p4 = ap_const_lv18_0) else "1";
    lshr_ln1_fu_687_p4 <= sub_ln62_fu_682_p2(31 downto 5);
    lshr_ln_fu_664_p1 <= prob_read;
    lshr_ln_fu_664_p4 <= lshr_ln_fu_664_p1(31 downto 5);
    or_ln1_fu_526_p3 <= (trunc_ln33_4_fu_514_p1 & ap_const_lv1_1);
    or_ln2_fu_777_p3 <= (ap_phi_mux_empty_phi_fu_228_p6 & ap_const_lv1_1);
    or_ln_fu_518_p3 <= (trunc_ln33_3_fu_510_p1 & ap_const_lv1_1);

    out_r_address0_assign_proc : process(icmp_ln48_reg_919, grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_address0, grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_address0, ap_CS_fsm_state6, ap_predicate_op128_call_state6, out_r_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if ((icmp_ln48_reg_919 = ap_const_lv1_1)) then 
                out_r_address0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_address0;
            elsif ((ap_predicate_op128_call_state6 = ap_const_boolean_1)) then 
                out_r_address0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_address0;
            else 
                out_r_address0 <= out_r_address0_local;
            end if;
        else 
            out_r_address0 <= out_r_address0_local;
        end if; 
    end process;


    out_r_address0_local_assign_proc : process(icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, zext_ln34_4_fu_535_p1, zext_ln34_fu_653_p1, ap_condition_671)
    begin
        if ((ap_const_boolean_1 = ap_condition_671)) then
            if ((icmp_ln48_fu_488_p2 = ap_const_lv1_1)) then 
                out_r_address0_local <= zext_ln34_fu_653_p1(10 - 1 downto 0);
            elsif (((icmp_ln51_fu_504_p2 = ap_const_lv1_0) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0))) then 
                out_r_address0_local <= zext_ln34_4_fu_535_p1(10 - 1 downto 0);
            else 
                out_r_address0_local <= "XXXXXXXXXX";
            end if;
        else 
            out_r_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;


    out_r_ce0_assign_proc : process(icmp_ln48_reg_919, grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_ce0, grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_ce0, ap_CS_fsm_state6, ap_predicate_op128_call_state6, out_r_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if ((icmp_ln48_reg_919 = ap_const_lv1_1)) then 
                out_r_ce0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_ce0;
            elsif ((ap_predicate_op128_call_state6 = ap_const_boolean_1)) then 
                out_r_ce0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_ce0;
            else 
                out_r_ce0 <= out_r_ce0_local;
            end if;
        else 
            out_r_ce0 <= out_r_ce0_local;
        end if; 
    end process;


    out_r_ce0_local_assign_proc : process(ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, grp_fu_330_p2)
    begin
        if ((((grp_fu_330_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_1) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((grp_fu_330_p2 = ap_const_lv1_1) and (icmp_ln51_fu_504_p2 = ap_const_lv1_0) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            out_r_ce0_local <= ap_const_logic_1;
        else 
            out_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    out_r_d0_assign_proc : process(icmp_ln48_reg_919, grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_d0, grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_d0, ap_CS_fsm_state6, ap_predicate_op128_call_state6, out_r_d0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if ((icmp_ln48_reg_919 = ap_const_lv1_1)) then 
                out_r_d0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_d0;
            elsif ((ap_predicate_op128_call_state6 = ap_const_boolean_1)) then 
                out_r_d0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_d0;
            else 
                out_r_d0 <= out_r_d0_local;
            end if;
        else 
            out_r_d0 <= out_r_d0_local;
        end if; 
    end process;


    out_r_d0_local_assign_proc : process(icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, or_ln1_fu_526_p3, trunc_ln1_fu_644_p3, ap_condition_671)
    begin
        if ((ap_const_boolean_1 = ap_condition_671)) then
            if ((icmp_ln48_fu_488_p2 = ap_const_lv1_1)) then 
                out_r_d0_local <= trunc_ln1_fu_644_p3;
            elsif (((icmp_ln51_fu_504_p2 = ap_const_lv1_0) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0))) then 
                out_r_d0_local <= or_ln1_fu_526_p3;
            else 
                out_r_d0_local <= "XXXXXXXX";
            end if;
        else 
            out_r_d0_local <= "XXXXXXXX";
        end if; 
    end process;


    out_r_we0_assign_proc : process(icmp_ln48_reg_919, grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_we0, grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_we0, ap_CS_fsm_state6, ap_predicate_op128_call_state6, out_r_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if ((icmp_ln48_reg_919 = ap_const_lv1_1)) then 
                out_r_we0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_50_1_fu_297_out_r_we0;
            elsif ((ap_predicate_op128_call_state6 = ap_const_boolean_1)) then 
                out_r_we0 <= grp_encode_bit_1_Pipeline_VITIS_LOOP_53_2_fu_281_out_r_we0;
            else 
                out_r_we0 <= (out_r_we0_out or ap_const_logic_0);
            end if;
        else 
            out_r_we0 <= (out_r_we0_out or ap_const_logic_0);
        end if; 
    end process;


    out_r_we0_local_assign_proc : process(ap_CS_fsm_state4, tmp_fu_450_p3, icmp_ln48_fu_488_p2, icmp_ln51_fu_504_p2, grp_fu_330_p2)
    begin
        if ((((grp_fu_330_p2 = ap_const_lv1_1) and (icmp_ln48_fu_488_p2 = ap_const_lv1_1) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((grp_fu_330_p2 = ap_const_lv1_1) and (icmp_ln51_fu_504_p2 = ap_const_lv1_0) and (icmp_ln48_fu_488_p2 = ap_const_lv1_0) and (tmp_fu_450_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            out_r_we0_local <= ap_const_logic_1;
        else 
            out_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_we0_out <= out_r_we0_local;
    r_2_fu_458_p2 <= std_logic_vector(unsigned(r_fu_94) + unsigned(ap_const_lv6_1));
    range_fu_364_p2 <= std_logic_vector(unsigned(add_ln41_fu_358_p2) - unsigned(low_read));
    select_ln43_1_fu_426_p3 <= 
        high_read when (bit_r(0) = '1') else 
        add_ln43_1_fu_413_p2;
    select_ln43_fu_419_p3 <= 
        add_ln43_fu_408_p2 when (bit_r(0) = '1') else 
        low_read;
    select_ln62_fu_706_p3 <= 
        sub_ln63_fu_677_p2 when (bit_r(0) = '1') else 
        add_ln62_fu_701_p2;
    shl_ln1_fu_765_p3 <= (ap_phi_mux_empty_45_phi_fu_239_p6 & ap_const_lv1_0);
    shl_ln33_fu_638_p2 <= std_logic_vector(shift_left(unsigned(ob_0_fu_114),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    sub_ln62_fu_682_p1 <= prob_read;
    sub_ln62_fu_682_p2 <= std_logic_vector(unsigned(ap_const_lv32_1000) - unsigned(sub_ln62_fu_682_p1));
    sub_ln63_fu_677_p0 <= prob_read;
    sub_ln63_fu_677_p2 <= std_logic_vector(signed(sub_ln63_fu_677_p0) - signed(zext_ln63_fu_673_p1));
    tmp_2_fu_478_p4 <= phi_ln64_1_fu_102(31 downto 15);
    tmp_3_fu_494_p4 <= phi_ln64_fu_106(31 downto 15);
    tmp_4_fu_543_p4 <= phi_ln64_fu_106(31 downto 14);
    tmp_fu_450_p3 <= r_fu_94(5 downto 5);
    trunc_ln1_fu_644_p3 <= (trunc_ln33_fu_634_p1 & ap_const_lv1_0);
    trunc_ln33_3_fu_510_p1 <= ob_0_fu_114(31 - 1 downto 0);
    trunc_ln33_4_fu_514_p1 <= ob_0_fu_114(7 - 1 downto 0);
    trunc_ln33_fu_634_p1 <= ob_0_fu_114(7 - 1 downto 0);
    trunc_ln47_1_fu_474_p1 <= phi_ln64_fu_106(15 - 1 downto 0);
    trunc_ln47_fu_470_p1 <= phi_ln64_1_fu_102(15 - 1 downto 0);
    trunc_ln56_1_fu_617_p1 <= phi_ln64_1_fu_102(14 - 1 downto 0);
    trunc_ln56_fu_591_p1 <= phi_ln64_fu_106(14 - 1 downto 0);
    xor_ln56_1_fu_621_p3 <= (xor_ln56_fu_611_p2 & trunc_ln56_1_fu_617_p1);
    xor_ln56_2_fu_585_p2 <= (bit_sel2_fu_577_p3 xor ap_const_lv1_1);
    xor_ln56_fu_611_p2 <= (bit_sel_fu_603_p3 xor ap_const_lv1_1);
    xor_ln_fu_595_p3 <= (xor_ln56_2_fu_585_p2 & trunc_ln56_fu_591_p1);
    zext_ln34_4_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oi_0_fu_110),64));
    zext_ln34_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oi_0_fu_110),64));
    zext_ln42_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(split_reg_884),32));
    zext_ln47_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln2_fu_777_p3),32));
    zext_ln59_fu_773_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_765_p3),32));
    zext_ln62_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_687_p4),32));
    zext_ln63_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_664_p4),32));
end behav;
