// ==============================================================
// Generated by Vitis HLS v2025.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module arith_encode_encode_chunk_Pipeline_VITIS_LOOP_33_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        oi_453_ph,
        nb_6_4_ph,
        ob_8_4_ph,
        pending_2,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        oi_453_out,
        oi_453_out_ap_vld,
        nb_6_4_out,
        nb_6_4_out_ap_vld,
        ob_8_4_out,
        ob_8_4_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] oi_453_ph;
input  [31:0] nb_6_4_ph;
input  [7:0] ob_8_4_ph;
input  [31:0] pending_2;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [31:0] oi_453_out;
output   oi_453_out_ap_vld;
output  [31:0] nb_6_4_out;
output   nb_6_4_out_ap_vld;
output  [7:0] ob_8_4_out;
output   ob_8_4_out_ap_vld;

reg ap_idle;
reg oi_453_out_ap_vld;
reg nb_6_4_out_ap_vld;
reg ob_8_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_143_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln34_fu_204_p1;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln34_fu_179_p2;
reg   [31:0] empty_fu_46;
wire   [31:0] pending_fu_149_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] ap_sig_allocacmp_p_load;
reg   [7:0] ob_8_4_fu_50;
wire   [7:0] ob_fu_166_p2;
reg   [31:0] nb_6_4_fu_54;
wire   [31:0] nb_fu_173_p2;
reg   [31:0] oi_453_fu_58;
wire   [31:0] oi_fu_198_p2;
wire    ap_block_pp0_stage0_01001;
reg    out_r_we0_local;
reg    out_r_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 empty_fu_46 = 32'd0;
#0 ob_8_4_fu_50 = 8'd0;
#0 nb_6_4_fu_54 = 32'd0;
#0 oi_453_fu_58 = 32'd0;
#0 ap_done_reg = 1'b0;
end

arith_encode_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_143_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            empty_fu_46 <= pending_fu_149_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_46 <= pending_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nb_6_4_fu_54 <= nb_6_4_ph;
        end else if (((icmp_ln34_fu_179_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            nb_6_4_fu_54 <= 32'd0;
        end else if (((icmp_ln34_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            nb_6_4_fu_54 <= nb_fu_173_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ob_8_4_fu_50 <= ob_8_4_ph;
        end else if (((icmp_ln34_fu_179_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ob_8_4_fu_50 <= 8'd0;
        end else if (((icmp_ln34_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ob_8_4_fu_50 <= ob_fu_166_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oi_453_fu_58 <= oi_453_ph;
        end else if (((icmp_ln34_fu_179_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            oi_453_fu_58 <= oi_fu_198_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_143_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_p_load = pending_2;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_143_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nb_6_4_out_ap_vld = 1'b1;
    end else begin
        nb_6_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_143_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ob_8_4_out_ap_vld = 1'b1;
    end else begin
        ob_8_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_143_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        oi_453_out_ap_vld = 1'b1;
    end else begin
        oi_453_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_179_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln33_fu_143_p2 = ((ap_sig_allocacmp_p_load == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_179_p2 = ((nb_fu_173_p2 == 32'd8) ? 1'b1 : 1'b0);

assign nb_6_4_out = nb_6_4_fu_54;

assign nb_fu_173_p2 = (nb_6_4_fu_54 + 32'd1);

assign ob_8_4_out = ob_8_4_fu_50;

assign ob_fu_166_p2 = ob_8_4_fu_50 << 8'd1;

assign oi_453_out = oi_453_fu_58;

assign oi_fu_198_p2 = (oi_453_fu_58 + 32'd1);

assign out_r_address0 = zext_ln34_fu_204_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = ob_fu_166_p2;

assign out_r_we0 = out_r_we0_local;

assign pending_fu_149_p2 = ($signed(ap_sig_allocacmp_p_load) + $signed(32'd4294967295));

assign zext_ln34_fu_204_p1 = oi_453_fu_58;

endmodule //arith_encode_encode_chunk_Pipeline_VITIS_LOOP_33_5
