// ==============================================================
// Generated by Vitis HLS v2025.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module arith_encode_encode_bit_Pipeline_VITIS_LOOP_50_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        oi_2_ph,
        nb_2_ph,
        ob_2_ph,
        pending_0,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        oi_2_out_i,
        oi_2_out_o,
        oi_2_out_o_ap_vld,
        nb_2_out_i,
        nb_2_out_o,
        nb_2_out_o_ap_vld,
        ob_2_out_i,
        ob_2_out_o,
        ob_2_out_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] oi_2_ph;
input  [31:0] nb_2_ph;
input  [31:0] ob_2_ph;
input  [31:0] pending_0;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
input  [31:0] oi_2_out_i;
output  [31:0] oi_2_out_o;
output   oi_2_out_o_ap_vld;
input  [31:0] nb_2_out_i;
output  [31:0] nb_2_out_o;
output   nb_2_out_o_ap_vld;
input  [31:0] ob_2_out_i;
output  [31:0] ob_2_out_o;
output   ob_2_out_o_ap_vld;

reg ap_idle;
reg[31:0] oi_2_out_o;
reg oi_2_out_o_ap_vld;
reg[31:0] nb_2_out_o;
reg nb_2_out_o_ap_vld;
reg[31:0] ob_2_out_o;
reg ob_2_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln50_fu_109_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln34_fu_193_p1;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln34_fu_156_p2;
wire   [31:0] add_ln34_fu_187_p2;
wire    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
wire   [31:0] add_ln33_fu_150_p2;
wire   [31:0] or_ln33_2_fu_142_p3;
reg   [31:0] empty_fu_42;
wire   [31:0] add_ln50_fu_115_p2;
reg   [31:0] ap_sig_allocacmp_p_load;
reg    out_r_we0_local;
wire   [7:0] or_ln34_3_fu_178_p3;
reg    out_r_ce0_local;
wire   [30:0] trunc_ln33_fu_134_p1;
wire   [6:0] trunc_ln33_1_fu_138_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 empty_fu_42 = 32'd0;
#0 ap_done_reg = 1'b0;
end

arith_encode_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln50_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            empty_fu_42 <= add_ln50_fu_115_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_42 <= pending_0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_p_load = pending_0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_42;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nb_2_out_o = nb_2_ph;
        end else if (((icmp_ln34_fu_156_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            nb_2_out_o = 32'd0;
        end else if (((icmp_ln34_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            nb_2_out_o = add_ln33_fu_150_p2;
        end else begin
            nb_2_out_o = nb_2_out_i;
        end
    end else begin
        nb_2_out_o = nb_2_out_i;
    end
end

always @ (*) begin
    if ((((icmp_ln34_fu_156_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln34_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        nb_2_out_o_ap_vld = 1'b1;
    end else begin
        nb_2_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ob_2_out_o = ob_2_ph;
        end else if (((icmp_ln34_fu_156_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ob_2_out_o = 32'd0;
        end else if (((icmp_ln34_fu_156_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ob_2_out_o = or_ln33_2_fu_142_p3;
        end else begin
            ob_2_out_o = ob_2_out_i;
        end
    end else begin
        ob_2_out_o = ob_2_out_i;
    end
end

always @ (*) begin
    if ((((icmp_ln34_fu_156_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln34_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ob_2_out_o_ap_vld = 1'b1;
    end else begin
        ob_2_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oi_2_out_o = oi_2_ph;
        end else if (((icmp_ln34_fu_156_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            oi_2_out_o = add_ln34_fu_187_p2;
        end else begin
            oi_2_out_o = oi_2_out_i;
        end
    end else begin
        oi_2_out_o = oi_2_out_i;
    end
end

always @ (*) begin
    if ((((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln34_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        oi_2_out_o_ap_vld = 1'b1;
    end else begin
        oi_2_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_156_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln33_fu_150_p2 = (nb_2_out_i + 32'd1);

assign add_ln34_fu_187_p2 = (oi_2_out_i + 32'd1);

assign add_ln50_fu_115_p2 = ($signed(ap_sig_allocacmp_p_load) + $signed(32'd4294967295));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln34_fu_156_p2 = ((add_ln33_fu_150_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_109_p2 = ((ap_sig_allocacmp_p_load == 32'd0) ? 1'b1 : 1'b0);

assign or_ln33_2_fu_142_p3 = {{trunc_ln33_fu_134_p1}, {1'd1}};

assign or_ln34_3_fu_178_p3 = {{trunc_ln33_1_fu_138_p1}, {1'd1}};

assign out_r_address0 = zext_ln34_fu_193_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = or_ln34_3_fu_178_p3;

assign out_r_we0 = out_r_we0_local;

assign trunc_ln33_1_fu_138_p1 = ob_2_out_i[6:0];

assign trunc_ln33_fu_134_p1 = ob_2_out_i[30:0];

assign zext_ln34_fu_193_p1 = oi_2_out_i;

endmodule //arith_encode_encode_bit_Pipeline_VITIS_LOOP_50_1
