// ==============================================================
// Generated by Vitis HLS v2025.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module arith_encode_encode_chunk (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        n,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] in_r_address0;
output   in_r_ce0;
input  [7:0] in_r_q0;
input  [31:0] n;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [7:0] out_r_d0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[7:0] out_r_d0;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_438;
wire    ap_CS_fsm_state4;
reg   [0:0] icmp_ln21_reg_938;
reg   [31:0] reg_443;
wire    ap_CS_fsm_state8;
reg   [31:0] reg_449;
reg   [31:0] reg_455;
reg   [31:0] reg_461;
reg   [31:0] reg_468;
reg   [31:0] reg_475;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln21_fu_528_p2;
wire    ap_CS_fsm_state3;
wire   [30:0] add_ln21_fu_533_p2;
reg   [30:0] add_ln21_reg_942;
reg   [31:0] flag_prob_reg_952;
wire    ap_CS_fsm_state5;
reg   [7:0] b_reg_957;
wire   [0:0] bit_fu_609_p1;
reg   [0:0] bit_reg_965;
wire    ap_CS_fsm_state6;
reg   [7:0] tree_addr_reg_970;
wire   [7:0] ctx_1_fu_622_p3;
reg   [7:0] ctx_1_reg_975;
wire   [3:0] j_1_fu_630_p2;
reg   [3:0] j_1_reg_980;
reg   [31:0] tree_load_reg_985;
wire    ap_CS_fsm_state7;
reg   [31:0] tree_addr_1_ret_reg_990;
wire    ap_CS_fsm_state9;
reg   [31:0] oi_1_reg_995;
wire    ap_CS_fsm_state11;
wire   [31:0] pending_2_fu_714_p2;
reg   [31:0] pending_2_reg_1004;
wire   [0:0] icmp_ln32_fu_730_p2;
reg   [0:0] icmp_ln32_reg_1010;
wire   [6:0] trunc_ln34_fu_736_p1;
reg   [6:0] trunc_ln34_reg_1014;
wire   [31:0] nb_fu_740_p2;
reg   [31:0] nb_reg_1020;
wire   [7:0] ob_2_fu_746_p3;
reg   [7:0] ob_2_reg_1027;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln34_fu_753_p2;
reg   [0:0] icmp_ln34_reg_1033;
wire   [7:0] ob_3_fu_758_p3;
reg   [7:0] ob_3_reg_1037;
wire   [31:0] grp_fu_433_p2;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state17;
reg   [7:0] tree_address0;
reg    tree_ce0;
reg    tree_we0;
reg   [31:0] tree_d0;
wire   [31:0] tree_q0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_idle;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_ready;
wire   [7:0] grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0;
wire   [31:0] grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0;
wire    grp_encode_bit_fu_325_ap_start;
wire    grp_encode_bit_fu_325_ap_done;
wire    grp_encode_bit_fu_325_ap_idle;
wire    grp_encode_bit_fu_325_ap_ready;
wire   [9:0] grp_encode_bit_fu_325_out_r_address0;
wire    grp_encode_bit_fu_325_out_r_ce0;
wire    grp_encode_bit_fu_325_out_r_we0;
wire   [7:0] grp_encode_bit_fu_325_out_r_d0;
reg   [0:0] grp_encode_bit_fu_325_bit_r;
wire   [31:0] grp_encode_bit_fu_325_ap_return_0;
wire   [31:0] grp_encode_bit_fu_325_ap_return_1;
wire   [31:0] grp_encode_bit_fu_325_ap_return_2;
wire   [31:0] grp_encode_bit_fu_325_ap_return_3;
wire   [31:0] grp_encode_bit_fu_325_ap_return_4;
wire   [31:0] grp_encode_bit_fu_325_ap_return_5;
wire   [31:0] grp_encode_bit_fu_325_ap_return_6;
wire    grp_encode_bit_1_fu_343_ap_start;
wire    grp_encode_bit_1_fu_343_ap_done;
wire    grp_encode_bit_1_fu_343_ap_idle;
wire    grp_encode_bit_1_fu_343_ap_ready;
wire   [9:0] grp_encode_bit_1_fu_343_out_r_address0;
wire    grp_encode_bit_1_fu_343_out_r_ce0;
wire    grp_encode_bit_1_fu_343_out_r_we0;
wire   [7:0] grp_encode_bit_1_fu_343_out_r_d0;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_0;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_1;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_2;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_3;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_4;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_5;
wire   [31:0] grp_encode_bit_1_fu_343_ap_return_6;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_idle;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_ready;
wire   [9:0] grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0;
wire   [7:0] grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0;
wire   [31:0] grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out_ap_vld;
wire   [31:0] grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out_ap_vld;
wire   [7:0] grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out_ap_vld;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_idle;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_ready;
wire   [9:0] grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0;
wire   [7:0] grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0;
wire   [31:0] grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out_ap_vld;
wire   [31:0] grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out_ap_vld;
wire   [7:0] grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out;
wire    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out_ap_vld;
reg   [3:0] j_reg_192;
wire    ap_CS_fsm_state10;
reg   [7:0] ctx_reg_203;
reg   [31:0] oi_453_ph_reg_214;
reg   [31:0] nb_6_4_ph_reg_224;
reg   [7:0] ob_8_4_ph_reg_236;
reg   [31:0] ap_phi_mux_oi_6_phi_fu_251_p4;
wire    ap_CS_fsm_state16;
reg   [7:0] ap_phi_mux_empty_phi_fu_260_p4;
reg   [31:0] ap_phi_mux_empty_44_phi_fu_269_p4;
wire   [31:0] oi_5_fu_816_p2;
reg   [31:0] ap_phi_mux_oi_7_phi_fu_278_p4;
wire   [0:0] icmp_ln34_1_fu_793_p2;
reg   [31:0] oi_251_ph_reg_285;
reg   [31:0] nb_6_2_ph_reg_295;
reg   [7:0] ob_8_2_ph_reg_307;
reg    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg;
wire    tree_we0_out;
reg    grp_encode_bit_fu_325_ap_start_reg;
wire    out_r_we0_out;
reg    grp_encode_bit_1_fu_343_ap_start_reg;
reg    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire   [63:0] zext_ln21_fu_538_p1;
wire   [63:0] zext_ln26_fu_613_p1;
wire   [0:0] tmp_1_fu_592_p3;
wire   [63:0] zext_ln34_1_fu_765_p1;
wire   [63:0] zext_ln34_3_fu_823_p1;
wire   [63:0] zext_ln34_fu_828_p1;
reg   [30:0] k_fu_72;
reg   [31:0] flag_prob_0_fu_76;
reg   [31:0] ob_8_0_fu_80;
reg   [31:0] nb_6_0_fu_84;
reg   [31:0] oi_0_fu_88;
reg   [31:0] low_0_fu_92;
reg   [31:0] high_0_fu_96;
reg   [31:0] pending_0_fu_100;
reg    in_r_ce0_local;
reg    tree_ce0_local;
reg   [7:0] tree_address0_local;
reg    tree_we0_local;
reg    out_r_we0_local;
reg   [7:0] out_r_d0_local;
reg    out_r_ce0_local;
reg   [9:0] out_r_address0_local;
wire   [7:0] shl_ln34_fu_809_p2;
wire   [31:0] zext_ln21_1_fu_524_p1;
wire   [7:0] zext_ln23_fu_600_p1;
wire   [7:0] lshr_ln25_fu_604_p2;
wire   [6:0] trunc_ln27_fu_618_p1;
wire   [17:0] tmp_fu_720_p4;
wire   [31:0] sub_ln34_fu_799_p2;
wire   [7:0] sub_ln34cast_fu_805_p1;
reg   [31:0] ap_return_preg;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg = 1'b0;
#0 grp_encode_bit_fu_325_ap_start_reg = 1'b0;
#0 grp_encode_bit_1_fu_343_ap_start_reg = 1'b0;
#0 grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg = 1'b0;
#0 grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg = 1'b0;
#0 k_fu_72 = 31'd0;
#0 flag_prob_0_fu_76 = 32'd0;
#0 ob_8_0_fu_80 = 32'd0;
#0 nb_6_0_fu_84 = 32'd0;
#0 oi_0_fu_88 = 32'd0;
#0 low_0_fu_92 = 32'd0;
#0 high_0_fu_96 = 32'd0;
#0 pending_0_fu_100 = 32'd0;
#0 ap_return_preg = 32'd0;
end

arith_encode_encode_chunk_tree_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
tree_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tree_address0),
    .ce0(tree_ce0),
    .we0(tree_we0),
    .d0(tree_d0),
    .q0(tree_q0)
);

arith_encode_encode_chunk_Pipeline_VITIS_LOOP_17_1 grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start),
    .ap_done(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done),
    .ap_idle(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_idle),
    .ap_ready(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_ready),
    .tree_address0(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0),
    .tree_ce0(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0),
    .tree_we0(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0),
    .tree_d0(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0)
);

arith_encode_encode_bit grp_encode_bit_fu_325(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_bit_fu_325_ap_start),
    .ap_done(grp_encode_bit_fu_325_ap_done),
    .ap_idle(grp_encode_bit_fu_325_ap_idle),
    .ap_ready(grp_encode_bit_fu_325_ap_ready),
    .low_read_6(reg_461),
    .low_read(reg_461),
    .high_read_6(reg_468),
    .high_read(reg_468),
    .pending_read(reg_475),
    .ob_read(reg_443),
    .nb_read(reg_449),
    .out_r_address0(grp_encode_bit_fu_325_out_r_address0),
    .out_r_ce0(grp_encode_bit_fu_325_out_r_ce0),
    .out_r_we0(grp_encode_bit_fu_325_out_r_we0),
    .out_r_d0(grp_encode_bit_fu_325_out_r_d0),
    .oi_read(reg_455),
    .prob_read(reg_438),
    .bit_r(grp_encode_bit_fu_325_bit_r),
    .ap_return_0(grp_encode_bit_fu_325_ap_return_0),
    .ap_return_1(grp_encode_bit_fu_325_ap_return_1),
    .ap_return_2(grp_encode_bit_fu_325_ap_return_2),
    .ap_return_3(grp_encode_bit_fu_325_ap_return_3),
    .ap_return_4(grp_encode_bit_fu_325_ap_return_4),
    .ap_return_5(grp_encode_bit_fu_325_ap_return_5),
    .ap_return_6(grp_encode_bit_fu_325_ap_return_6)
);

arith_encode_encode_bit_1 grp_encode_bit_1_fu_343(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_bit_1_fu_343_ap_start),
    .ap_done(grp_encode_bit_1_fu_343_ap_done),
    .ap_idle(grp_encode_bit_1_fu_343_ap_idle),
    .ap_ready(grp_encode_bit_1_fu_343_ap_ready),
    .low_read(reg_461),
    .high_read(reg_468),
    .pending_read(reg_475),
    .ob_read(reg_443),
    .nb_read(reg_449),
    .out_r_address0(grp_encode_bit_1_fu_343_out_r_address0),
    .out_r_ce0(grp_encode_bit_1_fu_343_out_r_ce0),
    .out_r_we0(grp_encode_bit_1_fu_343_out_r_we0),
    .out_r_d0(grp_encode_bit_1_fu_343_out_r_d0),
    .oi_read(reg_455),
    .prob_read(tree_load_reg_985),
    .bit_r(bit_reg_965),
    .ap_return_0(grp_encode_bit_1_fu_343_ap_return_0),
    .ap_return_1(grp_encode_bit_1_fu_343_ap_return_1),
    .ap_return_2(grp_encode_bit_1_fu_343_ap_return_2),
    .ap_return_3(grp_encode_bit_1_fu_343_ap_return_3),
    .ap_return_4(grp_encode_bit_1_fu_343_ap_return_4),
    .ap_return_5(grp_encode_bit_1_fu_343_ap_return_5),
    .ap_return_6(grp_encode_bit_1_fu_343_ap_return_6)
);

arith_encode_encode_chunk_Pipeline_VITIS_LOOP_33_5 grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start),
    .ap_done(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done),
    .ap_idle(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_idle),
    .ap_ready(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_ready),
    .oi_453_ph(oi_453_ph_reg_214),
    .nb_6_4_ph(nb_6_4_ph_reg_224),
    .ob_8_4_ph(ob_8_4_ph_reg_236),
    .pending_2(pending_2_reg_1004),
    .out_r_address0(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0),
    .out_r_ce0(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0),
    .out_r_we0(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0),
    .out_r_d0(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0),
    .oi_453_out(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out),
    .oi_453_out_ap_vld(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out_ap_vld),
    .nb_6_4_out(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out),
    .nb_6_4_out_ap_vld(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out_ap_vld),
    .ob_8_4_out(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out),
    .ob_8_4_out_ap_vld(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out_ap_vld)
);

arith_encode_encode_chunk_Pipeline_VITIS_LOOP_32_4 grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start),
    .ap_done(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done),
    .ap_idle(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_idle),
    .ap_ready(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_ready),
    .oi_251_ph(oi_251_ph_reg_285),
    .nb_6_2_ph(nb_6_2_ph_reg_295),
    .ob_8_2_ph(ob_8_2_ph_reg_307),
    .pending_2(pending_2_reg_1004),
    .out_r_address0(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0),
    .out_r_ce0(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0),
    .out_r_we0(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0),
    .out_r_d0(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0),
    .oi_251_out(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out),
    .oi_251_out_ap_vld(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out_ap_vld),
    .nb_6_2_out(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out),
    .nb_6_2_out_ap_vld(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out_ap_vld),
    .ob_8_2_out(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out),
    .ob_8_2_out_ap_vld(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_return_preg <= ap_phi_mux_oi_7_phi_fu_278_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_encode_bit_1_fu_343_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_encode_bit_1_fu_343_ap_start_reg <= 1'b1;
        end else if ((grp_encode_bit_1_fu_343_ap_ready == 1'b1)) begin
            grp_encode_bit_1_fu_343_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_encode_bit_fu_325_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln21_reg_938 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln21_reg_938 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_encode_bit_fu_325_ap_start_reg <= 1'b1;
        end else if ((grp_encode_bit_fu_325_ap_ready == 1'b1)) begin
            grp_encode_bit_fu_325_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg <= 1'b1;
        end else if ((grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_ready == 1'b1)) begin
            grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg <= 1'b1;
        end else if ((grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_ready == 1'b1)) begin
            grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg <= 1'b1;
        end else if ((grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_ready == 1'b1)) begin
            grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ctx_reg_203 <= ctx_1_reg_975;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ctx_reg_203 <= 8'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        flag_prob_0_fu_76 <= 32'd2048;
    end else if (((tmp_1_fu_592_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        flag_prob_0_fu_76 <= flag_prob_reg_952;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        high_0_fu_96 <= 32'd65535;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        high_0_fu_96 <= grp_encode_bit_fu_325_ap_return_5;
    end else if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        high_0_fu_96 <= grp_encode_bit_1_fu_343_ap_return_5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        j_reg_192 <= j_1_reg_980;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        j_reg_192 <= 4'd7;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_fu_72 <= 31'd0;
    end else if (((tmp_1_fu_592_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        k_fu_72 <= add_ln21_reg_942;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        low_0_fu_92 <= 32'd0;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        low_0_fu_92 <= grp_encode_bit_fu_325_ap_return_4;
    end else if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        low_0_fu_92 <= grp_encode_bit_1_fu_343_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nb_6_0_fu_84 <= 32'd0;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        nb_6_0_fu_84 <= grp_encode_bit_fu_325_ap_return_2;
    end else if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        nb_6_0_fu_84 <= grp_encode_bit_1_fu_343_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln34_reg_1033 == 1'd1))) begin
        nb_6_2_ph_reg_295 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln34_fu_753_p2 == 1'd0) & (icmp_ln32_reg_1010 == 1'd1))) begin
        nb_6_2_ph_reg_295 <= nb_reg_1020;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln34_reg_1033 == 1'd1))) begin
        nb_6_4_ph_reg_224 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln34_fu_753_p2 == 1'd0) & (icmp_ln32_reg_1010 == 1'd0))) begin
        nb_6_4_ph_reg_224 <= nb_reg_1020;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ob_8_0_fu_80 <= 32'd0;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ob_8_0_fu_80 <= grp_encode_bit_fu_325_ap_return_1;
    end else if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ob_8_0_fu_80 <= grp_encode_bit_1_fu_343_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln34_reg_1033 == 1'd1))) begin
                ob_8_2_ph_reg_307[1] <= 1'b0;
        ob_8_2_ph_reg_307[2] <= 1'b0;
        ob_8_2_ph_reg_307[3] <= 1'b0;
        ob_8_2_ph_reg_307[4] <= 1'b0;
        ob_8_2_ph_reg_307[5] <= 1'b0;
        ob_8_2_ph_reg_307[6] <= 1'b0;
        ob_8_2_ph_reg_307[7] <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln34_fu_753_p2 == 1'd0) & (icmp_ln32_reg_1010 == 1'd1))) begin
                ob_8_2_ph_reg_307[7 : 1] <= ob_2_fu_746_p3[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln34_reg_1033 == 1'd1))) begin
        ob_8_4_ph_reg_236 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln34_fu_753_p2 == 1'd0) & (icmp_ln32_reg_1010 == 1'd0))) begin
        ob_8_4_ph_reg_236 <= ob_3_fu_758_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oi_0_fu_88 <= 32'd0;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        oi_0_fu_88 <= grp_encode_bit_fu_325_ap_return_3;
    end else if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        oi_0_fu_88 <= grp_encode_bit_1_fu_343_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln34_reg_1033 == 1'd1))) begin
        oi_251_ph_reg_285 <= grp_fu_433_p2;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln34_fu_753_p2 == 1'd0) & (icmp_ln32_reg_1010 == 1'd1))) begin
        oi_251_ph_reg_285 <= oi_1_reg_995;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln34_reg_1033 == 1'd1))) begin
        oi_453_ph_reg_214 <= grp_fu_433_p2;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln34_fu_753_p2 == 1'd0) & (icmp_ln32_reg_1010 == 1'd0))) begin
        oi_453_ph_reg_214 <= oi_1_reg_995;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        pending_0_fu_100 <= 32'd0;
    end else if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pending_0_fu_100 <= grp_encode_bit_fu_325_ap_return_0;
    end else if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        pending_0_fu_100 <= grp_encode_bit_1_fu_343_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln21_reg_942 <= add_ln21_fu_533_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        b_reg_957 <= in_r_q0;
        flag_prob_reg_952 <= grp_encode_bit_fu_325_ap_return_6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bit_reg_965 <= bit_fu_609_p1;
        ctx_1_reg_975 <= ctx_1_fu_622_p3;
        j_1_reg_980 <= j_1_fu_630_p2;
        tree_addr_reg_970 <= zext_ln26_fu_613_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln21_reg_938 <= icmp_ln21_fu_528_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        icmp_ln32_reg_1010 <= icmp_ln32_fu_730_p2;
        nb_reg_1020 <= nb_fu_740_p2;
        oi_1_reg_995 <= grp_encode_bit_fu_325_ap_return_3;
        pending_2_reg_1004 <= pending_2_fu_714_p2;
        trunc_ln34_reg_1014 <= trunc_ln34_fu_736_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        icmp_ln34_reg_1033 <= icmp_ln34_fu_753_p2;
        ob_2_reg_1027[7 : 1] <= ob_2_fu_746_p3[7 : 1];
        ob_3_reg_1037[7 : 1] <= ob_3_fu_758_p3[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln21_reg_938 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln21_reg_938 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        reg_438 <= flag_prob_0_fu_76;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((icmp_ln21_reg_938 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln21_reg_938 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        reg_443 <= ob_8_0_fu_80;
        reg_449 <= nb_6_0_fu_84;
        reg_455 <= oi_0_fu_88;
        reg_461 <= low_0_fu_92;
        reg_468 <= high_0_fu_96;
        reg_475 <= pending_0_fu_100;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tree_addr_1_ret_reg_990 <= grp_encode_bit_1_fu_343_ap_return_6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tree_load_reg_985 <= tree_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_encode_bit_fu_325_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_encode_bit_fu_325_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_encode_bit_1_fu_343_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((icmp_ln32_reg_1010 == 1'd1)) begin
            ap_phi_mux_empty_44_phi_fu_269_p4 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out;
        end else if ((icmp_ln32_reg_1010 == 1'd0)) begin
            ap_phi_mux_empty_44_phi_fu_269_p4 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out;
        end else begin
            ap_phi_mux_empty_44_phi_fu_269_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_empty_44_phi_fu_269_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((icmp_ln32_reg_1010 == 1'd1)) begin
            ap_phi_mux_empty_phi_fu_260_p4 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out;
        end else if ((icmp_ln32_reg_1010 == 1'd0)) begin
            ap_phi_mux_empty_phi_fu_260_p4 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out;
        end else begin
            ap_phi_mux_empty_phi_fu_260_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_empty_phi_fu_260_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((icmp_ln32_reg_1010 == 1'd1)) begin
            ap_phi_mux_oi_6_phi_fu_251_p4 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out;
        end else if ((icmp_ln32_reg_1010 == 1'd0)) begin
            ap_phi_mux_oi_6_phi_fu_251_p4 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out;
        end else begin
            ap_phi_mux_oi_6_phi_fu_251_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_oi_6_phi_fu_251_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((icmp_ln34_1_fu_793_p2 == 1'd0)) begin
            ap_phi_mux_oi_7_phi_fu_278_p4 = ap_phi_mux_oi_6_phi_fu_251_p4;
        end else if ((icmp_ln34_1_fu_793_p2 == 1'd1)) begin
            ap_phi_mux_oi_7_phi_fu_278_p4 = oi_5_fu_816_p2;
        end else begin
            ap_phi_mux_oi_7_phi_fu_278_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_oi_7_phi_fu_278_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_return = ap_phi_mux_oi_7_phi_fu_278_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_encode_bit_fu_325_bit_r = 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_encode_bit_fu_325_bit_r = 1'd1;
    end else begin
        grp_encode_bit_fu_325_bit_r = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_r_ce0_local = 1'b1;
    end else begin
        in_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        out_r_address0 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        out_r_address0 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        out_r_address0 = grp_encode_bit_1_fu_343_out_r_address0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_address0 = grp_encode_bit_fu_325_out_r_address0;
    end else begin
        out_r_address0 = out_r_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        out_r_address0_local = zext_ln34_fu_828_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        out_r_address0_local = zext_ln34_3_fu_823_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        out_r_address0_local = zext_ln34_1_fu_765_p1;
    end else begin
        out_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        out_r_ce0 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        out_r_ce0 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        out_r_ce0 = grp_encode_bit_1_fu_343_out_r_ce0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_ce0 = grp_encode_bit_fu_325_out_r_ce0;
    end else begin
        out_r_ce0 = out_r_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        out_r_d0 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        out_r_d0 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        out_r_d0 = grp_encode_bit_1_fu_343_out_r_d0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_d0 = grp_encode_bit_fu_325_out_r_d0;
    end else begin
        out_r_d0 = out_r_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        out_r_d0_local = ob_2_reg_1027;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        out_r_d0_local = shl_ln34_fu_809_p2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        out_r_d0_local = ob_3_reg_1037;
    end else begin
        out_r_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        out_r_we0 = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        out_r_we0 = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        out_r_we0 = grp_encode_bit_1_fu_343_out_r_we0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_we0 = grp_encode_bit_fu_325_out_r_we0;
    end else begin
        out_r_we0 = (out_r_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((((icmp_ln34_1_fu_793_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state17) & (icmp_ln34_reg_1033 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (icmp_ln34_reg_1033 == 1'd1)))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tree_address0 = grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0;
    end else begin
        tree_address0 = tree_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tree_address0_local = tree_addr_reg_970;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        tree_address0_local = zext_ln26_fu_613_p1;
    end else begin
        tree_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tree_ce0 = grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0;
    end else begin
        tree_ce0 = tree_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        tree_ce0_local = 1'b1;
    end else begin
        tree_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tree_d0 = grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0;
    end else begin
        tree_d0 = tree_addr_1_ret_reg_990;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tree_we0 = grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0;
    end else begin
        tree_we0 = (tree_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tree_we0_local = 1'b1;
    end else begin
        tree_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln21_reg_938 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((tmp_1_fu_592_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_encode_bit_1_fu_343_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_encode_bit_fu_325_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln32_reg_1010 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_533_p2 = (k_fu_72 + 31'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bit_fu_609_p1 = lshr_ln25_fu_604_p2[0:0];

assign ctx_1_fu_622_p3 = {{trunc_ln27_fu_618_p1}, {bit_fu_609_p1}};

assign grp_encode_bit_1_fu_343_ap_start = grp_encode_bit_1_fu_343_ap_start_reg;

assign grp_encode_bit_fu_325_ap_start = grp_encode_bit_fu_325_ap_start_reg;

assign grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start = grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg;

assign grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start = grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg;

assign grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start = grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg;

assign grp_fu_433_p2 = (oi_1_reg_995 + 32'd1);

assign icmp_ln21_fu_528_p2 = (($signed(zext_ln21_1_fu_524_p1) < $signed(n)) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_730_p2 = ((tmp_fu_720_p4 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln34_1_fu_793_p2 = (($signed(ap_phi_mux_empty_44_phi_fu_269_p4) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_753_p2 = ((nb_reg_1020 == 32'd8) ? 1'b1 : 1'b0);

assign in_r_address0 = zext_ln21_fu_538_p1;

assign in_r_ce0 = in_r_ce0_local;

assign j_1_fu_630_p2 = ($signed(j_reg_192) + $signed(4'd15));

assign lshr_ln25_fu_604_p2 = b_reg_957 >> zext_ln23_fu_600_p1;

assign nb_fu_740_p2 = (grp_encode_bit_fu_325_ap_return_2 + 32'd1);

assign ob_2_fu_746_p3 = {{trunc_ln34_reg_1014}, {1'd0}};

assign ob_3_fu_758_p3 = {{trunc_ln34_reg_1014}, {1'd1}};

assign oi_5_fu_816_p2 = (ap_phi_mux_oi_6_phi_fu_251_p4 + 32'd1);

assign out_r_we0_out = out_r_we0_local;

assign pending_2_fu_714_p2 = (grp_encode_bit_fu_325_ap_return_0 + 32'd1);

assign shl_ln34_fu_809_p2 = ap_phi_mux_empty_phi_fu_260_p4 << sub_ln34cast_fu_805_p1;

assign sub_ln34_fu_799_p2 = (32'd8 - ap_phi_mux_empty_44_phi_fu_269_p4);

assign sub_ln34cast_fu_805_p1 = sub_ln34_fu_799_p2[7:0];

assign tmp_1_fu_592_p3 = j_reg_192[32'd3];

assign tmp_fu_720_p4 = {{grp_encode_bit_fu_325_ap_return_4[31:14]}};

assign tree_we0_out = tree_we0_local;

assign trunc_ln27_fu_618_p1 = ctx_reg_203[6:0];

assign trunc_ln34_fu_736_p1 = grp_encode_bit_fu_325_ap_return_1[6:0];

assign zext_ln21_1_fu_524_p1 = k_fu_72;

assign zext_ln21_fu_538_p1 = k_fu_72;

assign zext_ln23_fu_600_p1 = j_reg_192;

assign zext_ln26_fu_613_p1 = ctx_reg_203;

assign zext_ln34_1_fu_765_p1 = oi_1_reg_995;

assign zext_ln34_3_fu_823_p1 = ap_phi_mux_oi_6_phi_fu_251_p4;

assign zext_ln34_fu_828_p1 = oi_1_reg_995;

always @ (posedge ap_clk) begin
    ob_2_reg_1027[0] <= 1'b0;
    ob_3_reg_1037[0] <= 1'b1;
    ob_8_2_ph_reg_307[0] <= 1'b0;
end

endmodule //arith_encode_encode_chunk
