-- ==============================================================
-- Generated by Vitis HLS v2025.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity arith_encode_encode_chunk is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_r_ce0 : OUT STD_LOGIC;
    in_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    n : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of arith_encode_encode_chunk is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (18 downto 0) := "0000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (18 downto 0) := "0000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (18 downto 0) := "0000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (18 downto 0) := "0000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (18 downto 0) := "0000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (18 downto 0) := "0001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (18 downto 0) := "0010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (18 downto 0) := "0100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (18 downto 0) := "1000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_800 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000100000000000";
    constant ap_const_lv32_FFFF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000001111111111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_438 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln21_reg_938 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_443 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal reg_449 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_455 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_461 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_468 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_475 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln21_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln21_fu_533_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln21_reg_942 : STD_LOGIC_VECTOR (30 downto 0);
    signal flag_prob_reg_952 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal b_reg_957 : STD_LOGIC_VECTOR (7 downto 0);
    signal bit_fu_609_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal bit_reg_965 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tree_addr_reg_970 : STD_LOGIC_VECTOR (7 downto 0);
    signal ctx_1_fu_622_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ctx_1_reg_975 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_1_fu_630_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_reg_980 : STD_LOGIC_VECTOR (3 downto 0);
    signal tree_load_reg_985 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tree_addr_1_ret_reg_990 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal oi_1_reg_995 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal pending_2_fu_714_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal pending_2_reg_1004 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln32_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln34_fu_736_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln34_reg_1014 : STD_LOGIC_VECTOR (6 downto 0);
    signal nb_fu_740_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_reg_1020 : STD_LOGIC_VECTOR (31 downto 0);
    signal ob_2_fu_746_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ob_2_reg_1027 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal icmp_ln34_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_1033 : STD_LOGIC_VECTOR (0 downto 0);
    signal ob_3_fu_758_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ob_3_reg_1037 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_433_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal tree_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tree_ce0 : STD_LOGIC;
    signal tree_we0 : STD_LOGIC;
    signal tree_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tree_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_idle : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_ready : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0 : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0 : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_start : STD_LOGIC;
    signal grp_encode_bit_fu_325_ap_done : STD_LOGIC;
    signal grp_encode_bit_fu_325_ap_idle : STD_LOGIC;
    signal grp_encode_bit_fu_325_ap_ready : STD_LOGIC;
    signal grp_encode_bit_fu_325_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_encode_bit_fu_325_out_r_ce0 : STD_LOGIC;
    signal grp_encode_bit_fu_325_out_r_we0 : STD_LOGIC;
    signal grp_encode_bit_fu_325_out_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_bit_fu_325_bit_r : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_encode_bit_fu_325_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_fu_325_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_start : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_ap_done : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_ap_idle : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_ap_ready : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_encode_bit_1_fu_343_out_r_ce0 : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_out_r_we0 : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_out_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_bit_1_fu_343_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_idle : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_ready : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0 : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0 : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out_ap_vld : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out_ap_vld : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out_ap_vld : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_idle : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_ready : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0 : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0 : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out_ap_vld : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out_ap_vld : STD_LOGIC;
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out_ap_vld : STD_LOGIC;
    signal j_reg_192 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ctx_reg_203 : STD_LOGIC_VECTOR (7 downto 0);
    signal oi_453_ph_reg_214 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_6_4_ph_reg_224 : STD_LOGIC_VECTOR (31 downto 0);
    signal ob_8_4_ph_reg_236 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_oi_6_phi_fu_251_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_phi_mux_empty_phi_fu_260_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_44_phi_fu_269_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal oi_5_fu_816_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_oi_7_phi_fu_278_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln34_1_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal oi_251_ph_reg_285 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_6_2_ph_reg_295 : STD_LOGIC_VECTOR (31 downto 0);
    signal ob_8_2_ph_reg_307 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg : STD_LOGIC := '0';
    signal tree_we0_out : STD_LOGIC;
    signal grp_encode_bit_fu_325_ap_start_reg : STD_LOGIC := '0';
    signal out_r_we0_out : STD_LOGIC;
    signal grp_encode_bit_1_fu_343_ap_start_reg : STD_LOGIC := '0';
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal zext_ln21_fu_538_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_fu_613_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_592_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln34_1_fu_765_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_3_fu_823_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln34_fu_828_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_fu_72 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal flag_prob_0_fu_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ob_8_0_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal nb_6_0_fu_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal oi_0_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal low_0_fu_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal high_0_fu_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pending_0_fu_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_r_ce0_local : STD_LOGIC;
    signal tree_ce0_local : STD_LOGIC;
    signal tree_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal tree_we0_local : STD_LOGIC;
    signal out_r_we0_local : STD_LOGIC;
    signal out_r_d0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal out_r_ce0_local : STD_LOGIC;
    signal out_r_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln34_fu_809_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln21_1_fu_524_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln23_fu_600_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln25_fu_604_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln27_fu_618_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_720_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln34_fu_799_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln34cast_fu_805_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component arith_encode_encode_chunk_Pipeline_VITIS_LOOP_17_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        tree_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        tree_ce0 : OUT STD_LOGIC;
        tree_we0 : OUT STD_LOGIC;
        tree_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component arith_encode_encode_bit IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        low_read_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        low_read : IN STD_LOGIC_VECTOR (31 downto 0);
        high_read_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        high_read : IN STD_LOGIC_VECTOR (31 downto 0);
        pending_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_read : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_read : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        oi_read : IN STD_LOGIC_VECTOR (31 downto 0);
        prob_read : IN STD_LOGIC_VECTOR (31 downto 0);
        bit_r : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component arith_encode_encode_bit_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        low_read : IN STD_LOGIC_VECTOR (31 downto 0);
        high_read : IN STD_LOGIC_VECTOR (31 downto 0);
        pending_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_read : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_read : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        oi_read : IN STD_LOGIC_VECTOR (31 downto 0);
        prob_read : IN STD_LOGIC_VECTOR (31 downto 0);
        bit_r : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component arith_encode_encode_chunk_Pipeline_VITIS_LOOP_33_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        oi_453_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_6_4_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_8_4_ph : IN STD_LOGIC_VECTOR (7 downto 0);
        pending_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        oi_453_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        oi_453_out_ap_vld : OUT STD_LOGIC;
        nb_6_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        nb_6_4_out_ap_vld : OUT STD_LOGIC;
        ob_8_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        ob_8_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component arith_encode_encode_chunk_Pipeline_VITIS_LOOP_32_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        oi_251_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        nb_6_2_ph : IN STD_LOGIC_VECTOR (31 downto 0);
        ob_8_2_ph : IN STD_LOGIC_VECTOR (7 downto 0);
        pending_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        oi_251_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        oi_251_out_ap_vld : OUT STD_LOGIC;
        nb_6_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        nb_6_2_out_ap_vld : OUT STD_LOGIC;
        ob_8_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        ob_8_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component arith_encode_encode_chunk_tree_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    tree_U : component arith_encode_encode_chunk_tree_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tree_address0,
        ce0 => tree_ce0,
        we0 => tree_we0,
        d0 => tree_d0,
        q0 => tree_q0);

    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319 : component arith_encode_encode_chunk_Pipeline_VITIS_LOOP_17_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start,
        ap_done => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done,
        ap_idle => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_idle,
        ap_ready => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_ready,
        tree_address0 => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0,
        tree_ce0 => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0,
        tree_we0 => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0,
        tree_d0 => grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0);

    grp_encode_bit_fu_325 : component arith_encode_encode_bit
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_bit_fu_325_ap_start,
        ap_done => grp_encode_bit_fu_325_ap_done,
        ap_idle => grp_encode_bit_fu_325_ap_idle,
        ap_ready => grp_encode_bit_fu_325_ap_ready,
        low_read_6 => reg_461,
        low_read => reg_461,
        high_read_6 => reg_468,
        high_read => reg_468,
        pending_read => reg_475,
        ob_read => reg_443,
        nb_read => reg_449,
        out_r_address0 => grp_encode_bit_fu_325_out_r_address0,
        out_r_ce0 => grp_encode_bit_fu_325_out_r_ce0,
        out_r_we0 => grp_encode_bit_fu_325_out_r_we0,
        out_r_d0 => grp_encode_bit_fu_325_out_r_d0,
        oi_read => reg_455,
        prob_read => reg_438,
        bit_r => grp_encode_bit_fu_325_bit_r,
        ap_return_0 => grp_encode_bit_fu_325_ap_return_0,
        ap_return_1 => grp_encode_bit_fu_325_ap_return_1,
        ap_return_2 => grp_encode_bit_fu_325_ap_return_2,
        ap_return_3 => grp_encode_bit_fu_325_ap_return_3,
        ap_return_4 => grp_encode_bit_fu_325_ap_return_4,
        ap_return_5 => grp_encode_bit_fu_325_ap_return_5,
        ap_return_6 => grp_encode_bit_fu_325_ap_return_6);

    grp_encode_bit_1_fu_343 : component arith_encode_encode_bit_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_bit_1_fu_343_ap_start,
        ap_done => grp_encode_bit_1_fu_343_ap_done,
        ap_idle => grp_encode_bit_1_fu_343_ap_idle,
        ap_ready => grp_encode_bit_1_fu_343_ap_ready,
        low_read => reg_461,
        high_read => reg_468,
        pending_read => reg_475,
        ob_read => reg_443,
        nb_read => reg_449,
        out_r_address0 => grp_encode_bit_1_fu_343_out_r_address0,
        out_r_ce0 => grp_encode_bit_1_fu_343_out_r_ce0,
        out_r_we0 => grp_encode_bit_1_fu_343_out_r_we0,
        out_r_d0 => grp_encode_bit_1_fu_343_out_r_d0,
        oi_read => reg_455,
        prob_read => tree_load_reg_985,
        bit_r => bit_reg_965,
        ap_return_0 => grp_encode_bit_1_fu_343_ap_return_0,
        ap_return_1 => grp_encode_bit_1_fu_343_ap_return_1,
        ap_return_2 => grp_encode_bit_1_fu_343_ap_return_2,
        ap_return_3 => grp_encode_bit_1_fu_343_ap_return_3,
        ap_return_4 => grp_encode_bit_1_fu_343_ap_return_4,
        ap_return_5 => grp_encode_bit_1_fu_343_ap_return_5,
        ap_return_6 => grp_encode_bit_1_fu_343_ap_return_6);

    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357 : component arith_encode_encode_chunk_Pipeline_VITIS_LOOP_33_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start,
        ap_done => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done,
        ap_idle => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_idle,
        ap_ready => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_ready,
        oi_453_ph => oi_453_ph_reg_214,
        nb_6_4_ph => nb_6_4_ph_reg_224,
        ob_8_4_ph => ob_8_4_ph_reg_236,
        pending_2 => pending_2_reg_1004,
        out_r_address0 => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0,
        out_r_ce0 => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0,
        out_r_we0 => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0,
        out_r_d0 => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0,
        oi_453_out => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out,
        oi_453_out_ap_vld => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out_ap_vld,
        nb_6_4_out => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out,
        nb_6_4_out_ap_vld => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out_ap_vld,
        ob_8_4_out => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out,
        ob_8_4_out_ap_vld => grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out_ap_vld);

    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373 : component arith_encode_encode_chunk_Pipeline_VITIS_LOOP_32_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start,
        ap_done => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done,
        ap_idle => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_idle,
        ap_ready => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_ready,
        oi_251_ph => oi_251_ph_reg_285,
        nb_6_2_ph => nb_6_2_ph_reg_295,
        ob_8_2_ph => ob_8_2_ph_reg_307,
        pending_2 => pending_2_reg_1004,
        out_r_address0 => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0,
        out_r_ce0 => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0,
        out_r_we0 => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0,
        out_r_d0 => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0,
        oi_251_out => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out,
        oi_251_out_ap_vld => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out_ap_vld,
        nb_6_2_out => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out,
        nb_6_2_out_ap_vld => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out_ap_vld,
        ob_8_2_out => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out,
        ob_8_2_out_ap_vld => grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    ap_return_preg <= ap_phi_mux_oi_7_phi_fu_278_p4;
                end if; 
            end if;
        end if;
    end process;


    grp_encode_bit_1_fu_343_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_bit_1_fu_343_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_encode_bit_1_fu_343_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_bit_1_fu_343_ap_ready = ap_const_logic_1)) then 
                    grp_encode_bit_1_fu_343_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encode_bit_fu_325_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_bit_fu_325_ap_start_reg <= ap_const_logic_0;
            else
                if ((((icmp_ln21_reg_938 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln21_reg_938 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
                    grp_encode_bit_fu_325_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_bit_fu_325_ap_ready = ap_const_logic_1)) then 
                    grp_encode_bit_fu_325_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_ready = ap_const_logic_1)) then 
                    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_ready = ap_const_logic_1)) then 
                    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_ready = ap_const_logic_1)) then 
                    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ctx_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                ctx_reg_203 <= ctx_1_reg_975;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                ctx_reg_203 <= ap_const_lv8_1;
            end if; 
        end if;
    end process;

    flag_prob_0_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                flag_prob_0_fu_76 <= ap_const_lv32_800;
            elsif (((tmp_1_fu_592_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                flag_prob_0_fu_76 <= flag_prob_reg_952;
            end if; 
        end if;
    end process;

    high_0_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                high_0_fu_96 <= ap_const_lv32_FFFF;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                high_0_fu_96 <= grp_encode_bit_fu_325_ap_return_5;
            elsif (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                high_0_fu_96 <= grp_encode_bit_1_fu_343_ap_return_5;
            end if; 
        end if;
    end process;

    j_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                j_reg_192 <= j_1_reg_980;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_reg_192 <= ap_const_lv4_7;
            end if; 
        end if;
    end process;

    k_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                k_fu_72 <= ap_const_lv31_0;
            elsif (((tmp_1_fu_592_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                k_fu_72 <= add_ln21_reg_942;
            end if; 
        end if;
    end process;

    low_0_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                low_0_fu_92 <= ap_const_lv32_0;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                low_0_fu_92 <= grp_encode_bit_fu_325_ap_return_4;
            elsif (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                low_0_fu_92 <= grp_encode_bit_1_fu_343_ap_return_4;
            end if; 
        end if;
    end process;

    nb_6_0_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                nb_6_0_fu_84 <= ap_const_lv32_0;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                nb_6_0_fu_84 <= grp_encode_bit_fu_325_ap_return_2;
            elsif (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                nb_6_0_fu_84 <= grp_encode_bit_1_fu_343_ap_return_2;
            end if; 
        end if;
    end process;

    nb_6_2_ph_reg_295_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln34_reg_1033 = ap_const_lv1_1))) then 
                nb_6_2_ph_reg_295 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln34_fu_753_p2 = ap_const_lv1_0) and (icmp_ln32_reg_1010 = ap_const_lv1_1))) then 
                nb_6_2_ph_reg_295 <= nb_reg_1020;
            end if; 
        end if;
    end process;

    nb_6_4_ph_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln34_reg_1033 = ap_const_lv1_1))) then 
                nb_6_4_ph_reg_224 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln34_fu_753_p2 = ap_const_lv1_0) and (icmp_ln32_reg_1010 = ap_const_lv1_0))) then 
                nb_6_4_ph_reg_224 <= nb_reg_1020;
            end if; 
        end if;
    end process;

    ob_8_0_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ob_8_0_fu_80 <= ap_const_lv32_0;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                ob_8_0_fu_80 <= grp_encode_bit_fu_325_ap_return_1;
            elsif (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                ob_8_0_fu_80 <= grp_encode_bit_1_fu_343_ap_return_1;
            end if; 
        end if;
    end process;

    ob_8_2_ph_reg_307_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln34_reg_1033 = ap_const_lv1_1))) then 
                ob_8_2_ph_reg_307(1) <= '0';
                ob_8_2_ph_reg_307(2) <= '0';
                ob_8_2_ph_reg_307(3) <= '0';
                ob_8_2_ph_reg_307(4) <= '0';
                ob_8_2_ph_reg_307(5) <= '0';
                ob_8_2_ph_reg_307(6) <= '0';
                ob_8_2_ph_reg_307(7) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln34_fu_753_p2 = ap_const_lv1_0) and (icmp_ln32_reg_1010 = ap_const_lv1_1))) then 
                                ob_8_2_ph_reg_307(7 downto 1) <= ob_2_fu_746_p3(7 downto 1);
            end if; 
        end if;
    end process;

    ob_8_4_ph_reg_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln34_reg_1033 = ap_const_lv1_1))) then 
                ob_8_4_ph_reg_236 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln34_fu_753_p2 = ap_const_lv1_0) and (icmp_ln32_reg_1010 = ap_const_lv1_0))) then 
                ob_8_4_ph_reg_236 <= ob_3_fu_758_p3;
            end if; 
        end if;
    end process;

    oi_0_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                oi_0_fu_88 <= ap_const_lv32_0;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                oi_0_fu_88 <= grp_encode_bit_fu_325_ap_return_3;
            elsif (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                oi_0_fu_88 <= grp_encode_bit_1_fu_343_ap_return_3;
            end if; 
        end if;
    end process;

    oi_251_ph_reg_285_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln34_reg_1033 = ap_const_lv1_1))) then 
                oi_251_ph_reg_285 <= grp_fu_433_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln34_fu_753_p2 = ap_const_lv1_0) and (icmp_ln32_reg_1010 = ap_const_lv1_1))) then 
                oi_251_ph_reg_285 <= oi_1_reg_995;
            end if; 
        end if;
    end process;

    oi_453_ph_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln34_reg_1033 = ap_const_lv1_1))) then 
                oi_453_ph_reg_214 <= grp_fu_433_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln34_fu_753_p2 = ap_const_lv1_0) and (icmp_ln32_reg_1010 = ap_const_lv1_0))) then 
                oi_453_ph_reg_214 <= oi_1_reg_995;
            end if; 
        end if;
    end process;

    pending_0_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                pending_0_fu_100 <= ap_const_lv32_0;
            elsif (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                pending_0_fu_100 <= grp_encode_bit_fu_325_ap_return_0;
            elsif (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                pending_0_fu_100 <= grp_encode_bit_1_fu_343_ap_return_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln21_reg_942 <= add_ln21_fu_533_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                b_reg_957 <= in_r_q0;
                flag_prob_reg_952 <= grp_encode_bit_fu_325_ap_return_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                bit_reg_965 <= bit_fu_609_p1;
                ctx_1_reg_975 <= ctx_1_fu_622_p3;
                j_1_reg_980 <= j_1_fu_630_p2;
                tree_addr_reg_970 <= zext_ln26_fu_613_p1(8 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln21_reg_938 <= icmp_ln21_fu_528_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                icmp_ln32_reg_1010 <= icmp_ln32_fu_730_p2;
                nb_reg_1020 <= nb_fu_740_p2;
                oi_1_reg_995 <= grp_encode_bit_fu_325_ap_return_3;
                pending_2_reg_1004 <= pending_2_fu_714_p2;
                trunc_ln34_reg_1014 <= trunc_ln34_fu_736_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                icmp_ln34_reg_1033 <= icmp_ln34_fu_753_p2;
                    ob_2_reg_1027(7 downto 1) <= ob_2_fu_746_p3(7 downto 1);
                    ob_3_reg_1037(7 downto 1) <= ob_3_fu_758_p3(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln21_reg_938 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln21_reg_938 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then
                reg_438 <= flag_prob_0_fu_76;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((icmp_ln21_reg_938 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln21_reg_938 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then
                reg_443 <= ob_8_0_fu_80;
                reg_449 <= nb_6_0_fu_84;
                reg_455 <= oi_0_fu_88;
                reg_461 <= low_0_fu_92;
                reg_468 <= high_0_fu_96;
                reg_475 <= pending_0_fu_100;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                tree_addr_1_ret_reg_990 <= grp_encode_bit_1_fu_343_ap_return_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                tree_load_reg_985 <= tree_q0;
            end if;
        end if;
    end process;
    ob_2_reg_1027(0) <= '0';
    ob_3_reg_1037(0) <= '1';
    ob_8_2_ph_reg_307(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln21_reg_938, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state11, icmp_ln32_reg_1010, ap_CS_fsm_state12, grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done, grp_encode_bit_fu_325_ap_done, grp_encode_bit_1_fu_343_ap_done, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done, ap_CS_fsm_state15, ap_CS_fsm_state19, tmp_1_fu_592_p3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln21_reg_938 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((tmp_1_fu_592_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state11 => 
                if (((grp_encode_bit_fu_325_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln32_reg_1010 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                if (((grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln21_fu_533_p2 <= std_logic_vector(unsigned(k_fu_72) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_encode_bit_fu_325_ap_done)
    begin
        if ((grp_encode_bit_fu_325_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state15_blk_assign_proc : process(grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done)
    begin
        if ((grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state15_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state15_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state19_blk_assign_proc : process(grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done)
    begin
        if ((grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done)
    begin
        if ((grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_encode_bit_fu_325_ap_done)
    begin
        if ((grp_encode_bit_fu_325_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_encode_bit_1_fu_343_ap_done)
    begin
        if ((grp_encode_bit_1_fu_343_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_44_phi_fu_269_p4_assign_proc : process(icmp_ln32_reg_1010, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((icmp_ln32_reg_1010 = ap_const_lv1_1)) then 
                ap_phi_mux_empty_44_phi_fu_269_p4 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_nb_6_2_out;
            elsif ((icmp_ln32_reg_1010 = ap_const_lv1_0)) then 
                ap_phi_mux_empty_44_phi_fu_269_p4 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_nb_6_4_out;
            else 
                ap_phi_mux_empty_44_phi_fu_269_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_empty_44_phi_fu_269_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_260_p4_assign_proc : process(icmp_ln32_reg_1010, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((icmp_ln32_reg_1010 = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_260_p4 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ob_8_2_out;
            elsif ((icmp_ln32_reg_1010 = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_260_p4 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ob_8_4_out;
            else 
                ap_phi_mux_empty_phi_fu_260_p4 <= "XXXXXXXX";
            end if;
        else 
            ap_phi_mux_empty_phi_fu_260_p4 <= "XXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_oi_6_phi_fu_251_p4_assign_proc : process(icmp_ln32_reg_1010, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((icmp_ln32_reg_1010 = ap_const_lv1_1)) then 
                ap_phi_mux_oi_6_phi_fu_251_p4 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_oi_251_out;
            elsif ((icmp_ln32_reg_1010 = ap_const_lv1_0)) then 
                ap_phi_mux_oi_6_phi_fu_251_p4 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_oi_453_out;
            else 
                ap_phi_mux_oi_6_phi_fu_251_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_oi_6_phi_fu_251_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_oi_7_phi_fu_278_p4_assign_proc : process(ap_phi_mux_oi_6_phi_fu_251_p4, ap_CS_fsm_state16, oi_5_fu_816_p2, icmp_ln34_1_fu_793_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
            if ((icmp_ln34_1_fu_793_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_oi_7_phi_fu_278_p4 <= ap_phi_mux_oi_6_phi_fu_251_p4;
            elsif ((icmp_ln34_1_fu_793_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_oi_7_phi_fu_278_p4 <= oi_5_fu_816_p2;
            else 
                ap_phi_mux_oi_7_phi_fu_278_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_oi_7_phi_fu_278_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state16, ap_phi_mux_oi_7_phi_fu_278_p4, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_return <= ap_phi_mux_oi_7_phi_fu_278_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    bit_fu_609_p1 <= lshr_ln25_fu_604_p2(1 - 1 downto 0);
    ctx_1_fu_622_p3 <= (trunc_ln27_fu_618_p1 & bit_fu_609_p1);
    grp_encode_bit_1_fu_343_ap_start <= grp_encode_bit_1_fu_343_ap_start_reg;
    grp_encode_bit_fu_325_ap_start <= grp_encode_bit_fu_325_ap_start_reg;

    grp_encode_bit_fu_325_bit_r_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_encode_bit_fu_325_bit_r <= ap_const_lv1_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_encode_bit_fu_325_bit_r <= ap_const_lv1_1;
        else 
            grp_encode_bit_fu_325_bit_r <= "X";
        end if; 
    end process;

    grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start <= grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_ap_start_reg;
    grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_ap_start_reg;
    grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_ap_start_reg;
    grp_fu_433_p2 <= std_logic_vector(unsigned(oi_1_reg_995) + unsigned(ap_const_lv32_1));
    icmp_ln21_fu_528_p2 <= "1" when (signed(zext_ln21_1_fu_524_p1) < signed(n)) else "0";
    icmp_ln32_fu_730_p2 <= "1" when (tmp_fu_720_p4 = ap_const_lv18_0) else "0";
    icmp_ln34_1_fu_793_p2 <= "1" when (signed(ap_phi_mux_empty_44_phi_fu_269_p4) > signed(ap_const_lv32_0)) else "0";
    icmp_ln34_fu_753_p2 <= "1" when (nb_reg_1020 = ap_const_lv32_8) else "0";
    in_r_address0 <= zext_ln21_fu_538_p1(10 - 1 downto 0);
    in_r_ce0 <= in_r_ce0_local;

    in_r_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_r_ce0_local <= ap_const_logic_1;
        else 
            in_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_630_p2 <= std_logic_vector(unsigned(j_reg_192) + unsigned(ap_const_lv4_F));
    lshr_ln25_fu_604_p2 <= std_logic_vector(shift_right(unsigned(b_reg_957),to_integer(unsigned('0' & zext_ln23_fu_600_p1(8-1 downto 0)))));
    nb_fu_740_p2 <= std_logic_vector(unsigned(grp_encode_bit_fu_325_ap_return_2) + unsigned(ap_const_lv32_1));
    ob_2_fu_746_p3 <= (trunc_ln34_reg_1014 & ap_const_lv1_0);
    ob_3_fu_758_p3 <= (trunc_ln34_reg_1014 & ap_const_lv1_1);
    oi_5_fu_816_p2 <= std_logic_vector(unsigned(ap_phi_mux_oi_6_phi_fu_251_p4) + unsigned(ap_const_lv32_1));

    out_r_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state9, ap_CS_fsm_state11, grp_encode_bit_fu_325_out_r_address0, grp_encode_bit_1_fu_343_out_r_address0, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0, ap_CS_fsm_state15, ap_CS_fsm_state19, out_r_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_address0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_address0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_address0 <= grp_encode_bit_1_fu_343_out_r_address0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_address0 <= grp_encode_bit_fu_325_out_r_address0;
        else 
            out_r_address0 <= out_r_address0_local;
        end if; 
    end process;


    out_r_address0_local_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state17, ap_CS_fsm_state16, zext_ln34_1_fu_765_p1, zext_ln34_3_fu_823_p1, zext_ln34_fu_828_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            out_r_address0_local <= zext_ln34_fu_828_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            out_r_address0_local <= zext_ln34_3_fu_823_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_r_address0_local <= zext_ln34_1_fu_765_p1(10 - 1 downto 0);
        else 
            out_r_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;


    out_r_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state9, ap_CS_fsm_state11, grp_encode_bit_fu_325_out_r_ce0, grp_encode_bit_1_fu_343_out_r_ce0, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0, ap_CS_fsm_state15, ap_CS_fsm_state19, out_r_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_ce0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_ce0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_ce0 <= grp_encode_bit_1_fu_343_out_r_ce0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_ce0 <= grp_encode_bit_fu_325_out_r_ce0;
        else 
            out_r_ce0 <= out_r_ce0_local;
        end if; 
    end process;


    out_r_ce0_local_assign_proc : process(ap_CS_fsm_state13, ap_CS_fsm_state17, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            out_r_ce0_local <= ap_const_logic_1;
        else 
            out_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    out_r_d0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state9, ap_CS_fsm_state11, grp_encode_bit_fu_325_out_r_d0, grp_encode_bit_1_fu_343_out_r_d0, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0, ap_CS_fsm_state15, ap_CS_fsm_state19, out_r_d0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_d0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_d0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_d0 <= grp_encode_bit_1_fu_343_out_r_d0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_d0 <= grp_encode_bit_fu_325_out_r_d0;
        else 
            out_r_d0 <= out_r_d0_local;
        end if; 
    end process;


    out_r_d0_local_assign_proc : process(ob_2_reg_1027, ob_3_reg_1037, ap_CS_fsm_state13, ap_CS_fsm_state17, ap_CS_fsm_state16, shl_ln34_fu_809_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            out_r_d0_local <= ob_2_reg_1027;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            out_r_d0_local <= shl_ln34_fu_809_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_r_d0_local <= ob_3_reg_1037;
        else 
            out_r_d0_local <= "XXXXXXXX";
        end if; 
    end process;


    out_r_we0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state9, ap_CS_fsm_state11, grp_encode_bit_fu_325_out_r_we0, grp_encode_bit_1_fu_343_out_r_we0, grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0, grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0, out_r_we0_out, ap_CS_fsm_state15, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_r_we0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_32_4_fu_373_out_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            out_r_we0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_33_5_fu_357_out_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            out_r_we0 <= grp_encode_bit_1_fu_343_out_r_we0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_we0 <= grp_encode_bit_fu_325_out_r_we0;
        else 
            out_r_we0 <= (out_r_we0_out or ap_const_logic_0);
        end if; 
    end process;


    out_r_we0_local_assign_proc : process(icmp_ln34_reg_1033, ap_CS_fsm_state13, ap_CS_fsm_state17, ap_CS_fsm_state16, icmp_ln34_1_fu_793_p2)
    begin
        if ((((icmp_ln34_1_fu_793_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln34_reg_1033 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and (icmp_ln34_reg_1033 = ap_const_lv1_1)))) then 
            out_r_we0_local <= ap_const_logic_1;
        else 
            out_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_we0_out <= out_r_we0_local;
    pending_2_fu_714_p2 <= std_logic_vector(unsigned(grp_encode_bit_fu_325_ap_return_0) + unsigned(ap_const_lv32_1));
    shl_ln34_fu_809_p2 <= std_logic_vector(shift_left(unsigned(ap_phi_mux_empty_phi_fu_260_p4),to_integer(unsigned('0' & sub_ln34cast_fu_805_p1(8-1 downto 0)))));
    sub_ln34_fu_799_p2 <= std_logic_vector(unsigned(ap_const_lv32_8) - unsigned(ap_phi_mux_empty_44_phi_fu_269_p4));
    sub_ln34cast_fu_805_p1 <= sub_ln34_fu_799_p2(8 - 1 downto 0);
    tmp_1_fu_592_p3 <= j_reg_192(3 downto 3);
    tmp_fu_720_p4 <= grp_encode_bit_fu_325_ap_return_4(31 downto 14);

    tree_address0_assign_proc : process(ap_CS_fsm_state2, grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0, tree_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            tree_address0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_address0;
        else 
            tree_address0 <= tree_address0_local;
        end if; 
    end process;


    tree_address0_local_assign_proc : process(ap_CS_fsm_state6, tree_addr_reg_970, ap_CS_fsm_state10, zext_ln26_fu_613_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            tree_address0_local <= tree_addr_reg_970;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            tree_address0_local <= zext_ln26_fu_613_p1(8 - 1 downto 0);
        else 
            tree_address0_local <= "XXXXXXXX";
        end if; 
    end process;


    tree_ce0_assign_proc : process(ap_CS_fsm_state2, grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0, tree_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            tree_ce0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_ce0;
        else 
            tree_ce0 <= tree_ce0_local;
        end if; 
    end process;


    tree_ce0_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            tree_ce0_local <= ap_const_logic_1;
        else 
            tree_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    tree_d0_assign_proc : process(ap_CS_fsm_state2, tree_addr_1_ret_reg_990, grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            tree_d0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_d0;
        else 
            tree_d0 <= tree_addr_1_ret_reg_990;
        end if; 
    end process;


    tree_we0_assign_proc : process(ap_CS_fsm_state2, grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0, tree_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            tree_we0 <= grp_encode_chunk_Pipeline_VITIS_LOOP_17_1_fu_319_tree_we0;
        else 
            tree_we0 <= (tree_we0_out or ap_const_logic_0);
        end if; 
    end process;


    tree_we0_local_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            tree_we0_local <= ap_const_logic_1;
        else 
            tree_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tree_we0_out <= tree_we0_local;
    trunc_ln27_fu_618_p1 <= ctx_reg_203(7 - 1 downto 0);
    trunc_ln34_fu_736_p1 <= grp_encode_bit_fu_325_ap_return_1(7 - 1 downto 0);
    zext_ln21_1_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_fu_72),32));
    zext_ln21_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_fu_72),64));
    zext_ln23_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_192),8));
    zext_ln26_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ctx_reg_203),64));
    zext_ln34_1_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oi_1_reg_995),64));
    zext_ln34_3_fu_823_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_oi_6_phi_fu_251_p4),64));
    zext_ln34_fu_828_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oi_1_reg_995),64));
end behav;
