[hls]
relative_roots=/home/sadat-kabir/Work/COMP4601/labs/Project/comp4601-project/replication_full/hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=encode_bit/VITIS_LOOP_50_1 
syn.directive.pipeline=encode_bit/VITIS_LOOP_53_2 
syn.directive.pipeline=encode_chunk/VITIS_LOOP_17_1 
syn.directive.pipeline=encode_chunk/VITIS_LOOP_33_5 
syn.directive.pipeline=encode_chunk/VITIS_LOOP_32_4 
syn.directive.pipeline=arith_encode/VITIS_LOOP_66_1 
syn.directive.pipeline=arith_encode/Header 
syn.directive.pipeline=arith_encode/VITIS_LOOP_89_2 


